var searchData=
[
  ['magcache',['MagCache',['../structobsidian_1_1_mag_cache.html',1,'obsidian']]],
  ['magnetic_2ecpp',['magnetic.cpp',['../fwdmodel_2magnetic_8cpp.html',1,'']]],
  ['magnetic_2ecpp',['magnetic.cpp',['../serial_2magnetic_8cpp.html',1,'']]],
  ['magnetic_2ehpp',['magnetic.hpp',['../datatype_2magnetic_8hpp.html',1,'']]],
  ['magnetic_2ehpp',['magnetic.hpp',['../fwdmodel_2magnetic_8hpp.html',1,'']]],
  ['magnetic_2ehpp',['magnetic.hpp',['../serial_2magnetic_8hpp.html',1,'']]],
  ['magnetism_2ecpp',['magnetism.cpp',['../magnetism_8cpp.html',1,'']]],
  ['magparams',['MagParams',['../structobsidian_1_1_mag_params.html',1,'obsidian']]],
  ['magparamsprior',['MagParamsPrior',['../classobsidian_1_1prior_1_1_mag_params_prior.html',1,'obsidian::prior']]],
  ['magresults',['MagResults',['../structobsidian_1_1_mag_results.html',1,'obsidian']]],
  ['magsens',['magSens',['../namespaceobsidian_1_1fwd.html#a5b1a7afcec60eda91deea0aa5855c752',1,'obsidian::fwd::magSens(const Eigen::VectorXd &amp;xEdges, const Eigen::VectorXd &amp;yEdges, const Eigen::VectorXd &amp;zEdges, const Eigen::MatrixXd &amp;locations, const double &amp;bX, const double &amp;bY, const double &amp;bZ)'],['../namespaceobsidian_1_1fwd.html#a638d2c930ab44513d2190e02223ec43f',1,'obsidian::fwd::magSens(const Eigen::VectorXd &amp;xEdges, const Eigen::VectorXd &amp;yEdges, const Eigen::VectorXd &amp;zEdges, const Eigen::MatrixXd &amp;locations, const Eigen::VectorXd &amp;bX, const Eigen::VectorXd &amp;bY, const Eigen::VectorXd &amp;bZ)']]],
  ['magsensfunc',['magSensFunc',['../namespaceobsidian_1_1fwd_1_1detail.html#a372d2b0c6817e375e77f87b2ed4d459e',1,'obsidian::fwd::detail']]],
  ['magspec',['MagSpec',['../structobsidian_1_1_mag_spec.html',1,'obsidian']]],
  ['makegrid',['makeGrid',['../namespaceobsidian_1_1world.html#a596f764973b94e81dbafb87ed5f9705a',1,'obsidian::world']]],
  ['makeinterpparams',['makeInterpParams',['../namespaceobsidian_1_1fwd.html#aba35949193bfdf02851e1fc49c4fc757',1,'obsidian::fwd']]],
  ['markov_20chain_20monte_20carlo',['Markov Chain Monte Carlo',['../mcmc.html',1,'modules']]],
  ['mcmc_2ecpp',['mcmc.cpp',['../serial_2mcmc_8cpp.html',1,'']]],
  ['mcmc_2ehpp',['mcmc.hpp',['../serial_2mcmc_8hpp.html',1,'']]],
  ['mcmcsettings',['MCMCSettings',['../structstateline_1_1_m_c_m_c_settings.html',1,'stateline']]],
  ['mcmctypes_2ehpp',['mcmctypes.hpp',['../mcmctypes_8hpp.html',1,'']]],
  ['message',['Message',['../classstateline_1_1comms_1_1_message.html#a2b41bb746c040734f1dfb91a196a727c',1,'stateline::comms::Message::Message(const std::vector&lt; std::string &gt; &amp;addr, const Subject &amp;subj, const std::vector&lt; std::string &gt; &amp;d)'],['../classstateline_1_1comms_1_1_message.html#a995d42aacc53f9cda83a2c31b6e9f1fb',1,'stateline::comms::Message::Message(const Subject &amp;subj, const std::vector&lt; std::string &gt; &amp;d)'],['../classstateline_1_1comms_1_1_message.html#a13d262c02c94930c6ff2f46c62261cba',1,'stateline::comms::Message::Message(const std::vector&lt; std::string &gt; &amp;addr, const Subject &amp;subj)'],['../classstateline_1_1comms_1_1_message.html#a898a88fe9af96917d808ad2b5f2129f7',1,'stateline::comms::Message::Message(const Subject &amp;subj)']]],
  ['message',['Message',['../classstateline_1_1comms_1_1_message.html',1,'stateline::comms']]],
  ['messages_2ecpp',['messages.cpp',['../messages_8cpp.html',1,'']]],
  ['messages_2ehpp',['messages.hpp',['../messages_8hpp.html',1,'']]],
  ['metropolis_2ecpp',['metropolis.cpp',['../metropolis_8cpp.html',1,'']]],
  ['metropolis_2ehpp',['metropolis.hpp',['../metropolis_8hpp.html',1,'']]],
  ['minion',['Minion',['../classstateline_1_1comms_1_1_minion.html',1,'stateline::comms']]],
  ['minion',['Minion',['../classstateline_1_1comms_1_1_minion.html#a3404f903f51de68441d0114104498a07',1,'stateline::comms::Minion']]],
  ['minion_2ecpp',['minion.cpp',['../minion_8cpp.html',1,'']]],
  ['minion_2ehpp',['minion.hpp',['../minion_8hpp.html',1,'']]],
  ['modeltostring',['ModelToString',['../classobsidian_1_1_model_to_string.html',1,'obsidian']]],
  ['modules',['Modules',['../modules.html',1,'']]],
  ['monitortimeout',['monitorTimeout',['../namespacestateline_1_1comms.html#ad9f4f1741d91626f00a81de8ddf2eeba',1,'stateline::comms']]],
  ['monitortimeouts',['monitorTimeouts',['../namespacestateline_1_1comms.html#a07427e9205e333dc739398d1f4201eea',1,'stateline::comms']]],
  ['msgsignal',['MsgSignal',['../router_8hpp.html#ae479afe0b0db130e57b3e7f6f51683c8',1,'router.hpp']]],
  ['mspollrate',['msPollRate',['../structstateline_1_1_heartbeat_settings.html#a8cb988551fe6b90f3d1cb5c7f1c11d4b',1,'stateline::HeartbeatSettings::msPollRate()'],['../structstateline_1_1_delegator_settings.html#a6b60e948451fe1bd9085913bad140bf3',1,'stateline::DelegatorSettings::msPollRate()'],['../structstateline_1_1_worker_settings.html#a72e610823defbba4ee01c166244fea17',1,'stateline::WorkerSettings::msPollRate()']]],
  ['msrate',['msRate',['../structstateline_1_1_heartbeat_settings.html#a63521d662ad2f0c97ee2afc5eb98c049',1,'stateline::HeartbeatSettings']]],
  ['mstimeout',['msTimeout',['../structstateline_1_1_heartbeat_settings.html#a2189fe74fd731b5668a1cfa1f7415f35',1,'stateline::HeartbeatSettings']]],
  ['mt_2ecpp',['mt.cpp',['../serial_2mt_8cpp.html',1,'']]],
  ['mt_2ehpp',['mt.hpp',['../datatype_2mt_8hpp.html',1,'']]],
  ['mt_2ehpp',['mt.hpp',['../serial_2mt_8hpp.html',1,'']]],
  ['mt1d_2ecpp',['mt1d.cpp',['../mt1d_8cpp.html',1,'']]],
  ['mt1d_2ehpp',['mt1d.hpp',['../mt1d_8hpp.html',1,'']]],
  ['mtanisocache',['MtAnisoCache',['../structobsidian_1_1_mt_aniso_cache.html',1,'obsidian']]],
  ['mtanisoparams',['MtAnisoParams',['../structobsidian_1_1_mt_aniso_params.html',1,'obsidian']]],
  ['mtanisoparamsprior',['MtAnisoParamsPrior',['../classobsidian_1_1prior_1_1_mt_aniso_params_prior.html',1,'obsidian::prior']]],
  ['mtanisoresults',['MtAnisoResults',['../structobsidian_1_1_mt_aniso_results.html',1,'obsidian']]],
  ['mtanisospec',['MtAnisoSpec',['../structobsidian_1_1_mt_aniso_spec.html',1,'obsidian']]],
  ['mu',['mu',['../structobsidian_1_1distrib_1_1_multi_gaussian.html#a8bbb636184b3b4162e139375c53ca1ba',1,'obsidian::distrib::MultiGaussian::mu()'],['../namespaceobsidian_1_1fwd_1_1detail.html#a0b384a1fceff762f1b30043f8a349583',1,'obsidian::fwd::detail::MU()']]],
  ['multigaussian',['MultiGaussian',['../structobsidian_1_1distrib_1_1_multi_gaussian.html#a5a02514aa157a3990bd3b16e9e39e95a',1,'obsidian::distrib::MultiGaussian::MultiGaussian(const Eigen::VectorXd &amp;mu, const Eigen::MatrixXd &amp;sigma)'],['../structobsidian_1_1distrib_1_1_multi_gaussian.html#a01e6c79b8cb10cf47fcd36258da730d6',1,'obsidian::distrib::MultiGaussian::MultiGaussian(const Eigen::VectorXd &amp;mu, const Eigen::MatrixXd &amp;sigma, int w, int h)']]],
  ['multigaussian',['MultiGaussian',['../structobsidian_1_1distrib_1_1_multi_gaussian.html',1,'obsidian::distrib']]],
  ['multigaussian_2ecpp',['multigaussian.cpp',['../multigaussian_8cpp.html',1,'']]],
  ['multigaussian_2ehpp',['multigaussian.hpp',['../multigaussian_8hpp.html',1,'']]]
];
